enum Types {
  UPDATE_FILTER = "UPDATE_FILTER",
  SET_FILTER = "SET_FILTER",

  SET_PARENTS = "UPADTE_PARENTS",
  SET_DETECTED_OBJECTS = "UPDATE_DETECTED_OBJECTS",

  SET_CAPTURE = "SET_CAPTURE",
}

export default Types;
